_BASE_: "./CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  BACKBONE:
    NAME: "build_clip_swin_backbone"
    FREEZE_AT: 2  
  SWIN:
    OUT_FEATURES: ["stage5"]
  ROI_HEADS:
    NAME: "CLIPTransformerROIHeads"
    NUM_CLASSES: 80
    NMS_THRESH_TEST: 0.5
    IN_FEATURES: ["stage5"]    
  CLIP:
    NO_BOX_DELTA: True
    OFFLINE_RPN_NMS_THRESH: 0.9
    USE_TEXT_EMB_CLASSIFIER: "text-encoder"    
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)    