_BASE_: "./CLIP_fast_rcnn_R_50_C4.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 5
  #   NMS_THRESH_TEST: 0.5
  # CLIP:
  # #   NO_BOX_DELTA: True
  # #   OFFLINE_RPN_NMS_THRESH: 0.9 #default 0.7
  #   BG_CLS_LOSS_WEIGHT: 0.5
  #   FOCAL_SCALED_LOSS: 0.25
  #   FOCAL_SCALED_LOSS_ALPHA: -1
TEST:
  # #lvis allows up to 300 detections per image
  # DETECTIONS_PER_IMAGE: 100 #default 100, set equal POST_NMS_TOPK_TEST to detect all from RPN
  EVAL_PERIOD: 2500
SOLVER:
  IMS_PER_BATCH: 2 #was 8 for gpu memory, 2 for RN50x4
  BASE_LR: 0.001 #was 0.002
  #previous STEPS: (3000, 12000, 16000) (3000, 22000) (6000, 8000, 9000)
  STEPS: (18000, 60000) #decrease lr by factor of 10
  MAX_ITER: 90000
  WARMUP_ITERS: 5000 # set to 5000, too high cause nan loss 
  CHECKPOINT_PERIOD: 2500
INPUT:
  # MIN_SIZE_TRAIN_SAMPLING: choice
  # MIN_SIZE_TRAIN: (800,)
  # MAX_SIZE_TRAIN: 1333
  ROT:
    ENABLED: false
    TYPE: "choice"
    RANGE: [90,180,270]
  RANDOM_FLIP: "horizontal"
  LSJ:
    ENABLED: false
DATASETS:
  TRAIN: ("humanware_train_full",)
  TEST: ("humanware_val_full",)
