_BASE_: "./CLIP_fast_rcnn_R_50_C4.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 6
  # uncomment below for zeroshot inference
  #   NMS_THRESH_TEST: 0.5
  # CLIP:
  #   NO_BOX_DELTA: True
  #   OFFLINE_RPN_NMS_THRESH: 0.9
DATASETS:
  TRAIN: ("humanware_train",)
  TEST: ("humanware_test_cleaned",)
