_BASE_: "./CLIP_fast_rcnn_R_50_C4.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 6
    NMS_THRESH_TEST: 0.5
  CLIP:
    NO_BOX_DELTA: True
    OFFLINE_RPN_NMS_THRESH: 0.9
    VIS: True # Note: visualize the scores before multiplying RPN scores, if any
DATASETS:
  # TRAIN: ("humanware_train",)  #not needed for --eval-only
  # TEST: ("humanware_test",)  
  TRAIN: ("lvis_v1_train_custom_img",) #not needed for --eval-only
  TEST: ("lvis_v1_val_custom_img",)  #custom images
  # TRAIN: ("humanware_train_custom_img",) #custom images only works with lvis settings? need lvis model?
  # TEST: ("humanware_val_custom_img",)
