_BASE_: "./CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 5
    NMS_THRESH_TEST: 0.2
    SCORE_THRESH_TEST: 0.1
  CLIP:
    # NO_BOX_DELTA: True
    OFFLINE_RPN_NMS_THRESH: 0.9
  # VIS: True
DATASETS:
  TRAIN: ("humanware_train_full",)
  TEST: ("humanware_test_basic",)
