_BASE_: "./CLIP_fast_rcnn_R_50_C4_ovd.yaml"
MODEL:
  ROI_HEADS:
    NUM_CLASSES: 5
    NMS_THRESH_TEST: 0.6 #Defaults to 0.5 
    SCORE_THRESH_TEST: 0.001 #Defaults to 0.001
    SOFT_NMS_ENABLED: False #Defaults to False
  CLIP:
    # NO_BOX_DELTA: False #default false set to True only detecting OOD class or for zero-shot (model aren't trained on those class), set false improves detection on base classes (box delta realigns prediction coordinates based on learned class head)
    OFFLINE_RPN_NMS_THRESH: 0.7 #default 0.7
    #BG_CLS_SCORE: False #include background bboxes and scores
    OFFLINE_RPN_PRE_NMS_TOPK_TEST: 12000 #default 6000
    OFFLINE_RPN_POST_NMS_TOPK_TEST: 2000 #default 1000
    CLS_ID_NMS: True #default False
    CROP_REGION_TYPE: "RPN" #default "RPN" can switch to GT (clip style evaluation)
DATASETS:
  TRAIN: ("humanware_train_basic",)
#  TEST: ("humanware_test_custom",)
#  TEST: ("humanware_test_basic",)
#  TEST: ("humanware_test_collected",)
  TEST: ("humanware_test_full",)
#  TEST: ("humanware_test_awake",)
INPUT:
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
TEST:
  DETECTIONS_PER_IMAGE: 1000 #default 100 set equal POST_NMS_TOPK_TEST to detect all from RPN