_BASE_: ./CLIP_fast_rcnn_R_50_C4_ovd.yaml
MODEL:
  MASK_ON: False
  ROI_HEADS:
    NUM_CLASSES: 5
    NMS_THRESH_TEST: 0.2
    SCORE_THRESH_TEST: 0.6
  CLIP:
    OFFLINE_RPN_NMS_THRESH: 0.9
    VIS: True
DATASETS:
  TEST: ("lvis_v1_val_custom_img",)
  TRAIN: ("lvis_v1_train_custom_img",)
