DATASETS:
  TEST: ("lvis_v1_val_custom_img",)
  TRAIN: ("lvis_v1_train_custom_img",)
MODEL:
  CLIP:
    OFFLINE_RPN_NMS_THRESH: 0.9
    VIS: true
  MASK_ON: false
  ROI_HEADS:
    NMS_THRESH_TEST: 0.3
    NUM_CLASSES: 5
    SCORE_THRESH_TEST: 0.6
_BASE_: ./CLIP_fast_rcnn_R_50_C4_ovd.yaml
