DATASETS:
  TEST: ("lvis_v1_val_custom_img",)
  TRAIN: ("lvis_v1_train_custom_img",)
MODEL:
  CLIP:
    OFFLINE_RPN_NMS_THRESH: 0.7 #default 0.7
    VIS: true
    OFFLINE_RPN_PRE_NMS_TOPK_TEST: 12000 #default 6000
    OFFLINE_RPN_POST_NMS_TOPK_TEST: 2000 #default 1000
    CROP_REGION_TYPE: "RPN"
    #TODO merge with main to update below attributes and check for outputs
    #CLS_ID_NMS: True
    #BG_CLS_SCORE: True #generate all rpn bbox and scores include background bboxes and scores
  MASK_ON: false
  ROI_HEADS:
    NMS_THRESH_TEST: 0.6 #default 0.5
    NUM_CLASSES: 7
    SCORE_THRESH_TEST: 0.01 #default 0.001
_BASE_: ./CLIP_fast_rcnn_R_50_C4_ovd.yaml
TEST:
  DETECTIONS_PER_IMAGE: 1000 #default 100
INPUT:
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 1333
